### ISSUE TITLE
تطوير للextension أو إضافات 

### ISSUE THREAD

**Issue by m-1226** [nagwan/azkar-remider-chrome-extension#5]
السلام عليكم ورحمه الله وبركاته
قبل اي شيء 
عاوز اقول إن الextension اللهم بارك جميلة و فكرتها جميلة جدا 
ف ربنا يجازيكِ عنها وعن كل شخص هينزلها خير الجزاء بإذن الله 

فقط 
اسمحي لشخصي المتواضع بأنه يقول بعض الاضافات والأفكار ليها 
- 
- الاذكار مثلا محتاجة تكون أكثر من اللي موجودة او المعروضة
ويتم عمل مثلا خيار علي حسب المدة المتوفرة بدل عشر دقائق  يعني تبقي علي حسب اختيار المستخدم 
3 دقائق 5 كده   

انا راجعت الكود كويس  وعندي بس اذا تسمحي بده شوية إضافات 
- بفضل لو يتعمل ملف json مخصص لكل الاذكار ومن خلال الimport في المكان اللي محتاجينه فيه نقدر نستخدمها بسهولة لانه اذا الاذكار كبرت ف لازم نفصلها اكيد في ملف لوحده 

عندي بس طلب بسيط 
 اذا تسمحي لي إني اعمل fork واخد نسخة اشارك و اساعد معاكِ في تطوير الextension واضيف كل الاضافات اللي قلتها فوق وبعض الأفكار اللي حابب أنها تضاف للextension 
  ف اكيد هكون سعيد بده جدا 
بس كده
جزاكِ الله كل خير علي الextension مرة تانية 

بعتذر علي الإطالة والازعاج 

وكل عام وانتم بخير بمناسبة الشهر الكريم 
اعاده الله عليكم وعلي الأسرة الكريمة بالخير واليمن والبركات إن شاء الله

**Comment by nagwan** [comment]
السلام عليكم ورحمة الله وبركاته 
اولا حابه اشكر حضرتك جدا على الافكار الجميله 
و هكون سعيده جدا اذا فتحت PR و ساهمنا في تطوير ال extension ان شاء الله باي فكره تيجي في بالك

بالنسبه لاول نقطه و هي السماح للمستخدم باختيار الفتره الزمنيه ما بين كل ذكر هي بالفعل implementated في اخر تحديث لل extension  

اما بالنسبه لل json file فكره جميله شكرا جدا 

ان شاء الله هضيف readme file علشان تعرف ال upcoming features و تقدر تساهم في تطوير ايا منهم اذا حابب

**Comment by nagwan** [comment]
السلام عليكم ورحمة الله وبركاته
اولا حابه اشكر حضرتك جدا على الافكار الجميله
و هكون سعيده جدا اذا فتحت PR و ساهمنا في تطوير ال extension ان شاء الله باي فكره تيجي في بالك

بالنسبه لاول نقطه و هي السماح للمستخدم باختيار الفتره الزمنيه ما بين كل ذكر هي بالفعل implementated في اخر تحديث لل extension

اما بالنسبه لل json file فكره جميله جدا لكن بيحصل error لان سواء ال background and the pop -up files  مش modules 

فباذن الله نحاول نحسن الكود تدريجيا 

ان شاء الله هضيف readme file علشان تعرف ال upcoming features و تقدر تساهم في تطوير ايا منهم اذا حابب

**Comment by nagwan** [comment]
شكرا ليك جدا على وقتك و مجهودك و شغفك بتطوير ال extension 
ربنا يتقبل منا و منكم صالح الاعمال

بالنسبه لجزئيه التنظيم انا ضفت الاذكار في ملف js خاص بيها فدا بيادي الهدف التنظيمي 

تقدر تعمل clone و تبدا تعمل prs و ان شاء الله اعمل review و نرفع عالطول 
و كمان اي فكره تحب ننفذها ونشتغل عليها تقدر تبدا بيها discussion و نفتح بيها feature request و نبدا نشتغل عليها ان شاء الله 

شكرا جدا مره تانيه 
و بالتوفيق يارب

**Comment by nagwan** [comment]
شكرا ليك جدا على وقتك و مجهودك و شغفك بتطوير ال extension
ربنا يتقبل منا و منكم صالح الاعمال

بالنسبه لجزئيه التنظيم انا ضفت الاذكار في ملف js خاص بيها فدا بيادي الهدف التنظيمي

تقدر تعمل clone و تبدا تعمل prs و ان شاء الله اعمل review و نرفع عالطول
و كمان اي فكره تحب ننفذها ونشتغل عليها تقدر تبدا بيها [discussion](https://github.com/nagwan/azkar-remider-chrome-extension/discussions
) و نفتح بيها feature request و نبدا نشتغل عليها ان شاء الله

شكرا جدا مره تانيه
و بالتوفيق ان شاء الله
